# Overlays for the Odroid platform

dtbo-y += \
	can0.dtbo \
	dht11.dtbo \
	display_vu8s.dtbo \
	i2c0.dtbo \
	i2c1.dtbo \
	onewire.dtbo \
	pwm15.dtbo \
	pwm3.dtbo \
	pwm7.dtbo \
	pwm8.dtbo \
	pwm15.dtbo \
	rknpu.dtbo \
	spi0.dtbo \
	uart0-with-ctsrts.dtbo \
	uart0.dtbo \
	uart1.dtbo

targets += $(dtbo-y)
always := $(dtbo-y)
